import Head from 'next/head'
import {
  Container,
  Main,
  Header,
  Title,
  Description
} from '../components/sharedstyles'
import Cards from '../components/cards'

export default function Home() {
     
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Main>
        <Title>Venha para o StadyMaster</Title>
        <Cards />
      </Main>
    </Container>
  )
}
